### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by edu1998** [Jack-Overflow/rxjs-http-client#5]
hi everyone, there is an issue when i try to make a put:

![image](https://user-images.githubusercontent.com/35113581/70834143-97c21d80-1dc7-11ea-85e7-dd33e079d818.png)

`public put$(url: string, data: whatever): Observable<IHttpResponse> {
      return this._http.put(
          `${this._baseUrl}/${url}`,
          {body: data, headers: {Authorization: 'Bearer ' + this._token}},
      );
    }`

**Comment by Jack-Overflow** [comment]
Hello, 

Sorry you were having this issue this problem seems to have affected only the put method due to the HttpRequestConfigurationsEnum PUT property accidentally being set to 'GET' instead of 'PUT' I have fixed this issue in the latest release. Please update to version 1.3.2 to fix this problem.

Thanks.
